spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/gym_db_task3?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.jdbc.Driver
    username: admin
    password: 2580Sabi2580
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"